<template>
  <div class="container">
    <BreadCrumb></BreadCrumb>
    <div class="page">
      <div class="left_all">
        <div class="left_slider">
          <Slider :siderItem="siderItem"></Slider>
        </div>
      </div>
      <div class="mainer">
        <el-row class="title">审批列表</el-row>
        <QuickSearch :queryitem="queryItem"></QuickSearch>
        <el-row class="marginb20">
          <el-radio-group v-model="approvelStatus">
            <el-radio-button label="参会名单收集中"></el-radio-button>
            <el-radio-button label="已锁定"></el-radio-button>
            <el-radio-button label="已结束"></el-radio-button>
          </el-radio-group>
        </el-row>
        <div v-if="approvelStatus === '参会名单收集中'">
          <ApprovelList :approvelDataList="approvelDataList" :hasdetail="true"></ApprovelList>
        </div>
        <div v-else-if="approvelStatus === '已锁定'">
          <ApprovelList :approvelDataList="approvelDataList"></ApprovelList>
        </div>
        <div v-else>
          <ApprovelList :approvelDataList="approvelDataListEnd" :status="'hadEnd'"></ApprovelList>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import BreadCrumb from "../components/breadCurmb";
import Slider from "../components/Slider";
import QuickSearch from "../components/quickSearch";
import ApprovelList from "../components/approvelItem";
export default {
  data() {
    return {
      siderItem: "审批列表",
      queryItem: [
        {
          title: "会议名称",
          input: "",
          type: "input",
        },
        {
          title: "会议编号",
          input: "",
          type: "input",
        },
        {
          title: "会议开始日期",
          input: "",
          type: "date",
        },
        {
          title: "会议结束日期",
          input: "",
          type: "date",
        },
      ],
      approvelStatus: "参会名单收集中",
      approvelDataList: [
        {
          name: "广州淋巴癌会议",
          startTime: "2020-11-11",
          endTime: "2020-11-11",
          meetNum: "EPG567",
          meetingStatus:'参会名单收集中',
          gross: 600000,
          cost: 560000,
          trip: {
            tktdeadline: "2020-11-10 14:59:00",
            guid: "0f9d39b9-9134-3e8e-99e2-8508ecea88e0",
            tr_no: null,
            original_tr_no: null,
            eorder_no: "EORDER-202011100233",
            cltid: "2541",
            list: [
              {
                seqno: 1,
                clientname: "",
                bookname: "授权人",
                paxname: "授权人1",
                staffno: "d1000",
                routetype: "D",
                hospital:'上海市第一人民医院',
                deadlineapprovel:"2020-11-11 12:55:26",
                depdate: "2020-11-26",
                arrdate: "2020-11-26",
                mobileno: "15000290628",
                jdeno: "d1000",
                IdNo: "310104198212232865",
                CUICode: "110104198212232864",
                profileid: "1537170",
                type: null,
                price: null,
                servicefee: "10.00",
                processfee: "0.00",
                tax: null,
                status: "已取消",
                approvelstatus: "待审批",
                trips: [
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "520.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "520.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                ],
                hotels: [],
                trans: [],
                foods: [],
                others: [],
                visas: [],
              },
              {
                seqno: 2,
                clientname: "",
                bookname: "授权人",
                paxname: "授权人3",
                staffno: "d1000",
                routetype: "D",
                hospital:'上海市第一人民医院',
                deadlineapprovel:"2020-11-09 12:45:26",
                depdate: "2020-11-26",
                arrdate: "2020-11-26",
                mobileno: "15000290628",
                jdeno: "d1000",
                IdNo: "310104198212232864",
                CUICode: "110104198212232864",
                profileid: "1537170",
                type: null,
                price: null,
                servicefee: "10.00",
                processfee: "0.00",
                tax: null,
                status: "已取消",
                approvelstatus: "待审批",
                trips: [
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "780.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                ],
                hotels: [],
                trans: [],
                foods: [],
                others: [],
                visas: [],
              },
              {
                seqno: 3,
                clientname: "",
                bookname: "授权人",
                paxname: "授权人2",
                staffno: "d1000",
                routetype: "D",
                hospital:'上海市第一人民医院',
                deadlineapprovel:"2020-11-09 12:45:26",
                depdate: "2020-11-26",
                arrdate: "2020-11-26",
                mobileno: "15000290628",
                jdeno: "d1000",
                IdNo: "310104198212232865",
                CUICode: "110104198212232864",
                profileid: "1537170",
                type: null,
                price: null,
                servicefee: "10.00",
                processfee: "0.00",
                tax: null,
                status: "已取消",
                approvelstatus: "已拒绝",
                trips: [
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "1520.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                ],
                hotels: [],
                trans: [],
                foods: [],
                others: [],
                visas: [],
              },
              
            ],
          },
        },
        {
          name: "上海肝癌会议",
          startTime: "2020-11-11",
          endTime: "2020-11-11",
          meetNum: "EPG567",
          gross: 600000,
          cost: 120000,
          trip: {
            tktdeadline: "2020-11-10 14:59:00",
            guid: "0f9d39b9-9134-3e8e-99e2-8508ecea88e0",
            tr_no: null,
            original_tr_no: null,
            eorder_no: "EORDER-202011100233",
            cltid: "2541",
            list: [
              {
                seqno: 1,
                clientname: "",
                bookname: "授权人",
                paxname: "授权人1",
                staffno: "d1000",
                routetype: "D",
                hospital:'上海市第一人民医院',
                deadlineapprovel:"2020-11-11 12:55:26",
                depdate: "2020-11-26",
                arrdate: "2020-11-26",
                mobileno: "15000290628",
                jdeno: "d1000",
                IdNo: "310104198212232865",
                CUICode: "110104198212232862",
                profileid: "1537170",
                type: null,
                price: null,
                servicefee: "10.00",
                processfee: "0.00",
                tax: null,
                status: "已取消",
                approvelstatus: "待审批",
                trips: [
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "520.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "520.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                ],
                hotels: [],
                trans: [],
                foods: [],
                others: [],
                visas: [],
              },
              {
                seqno: 2,
                clientname: "",
                bookname: "授权人",
                paxname: "授权人3",
                staffno: "d1000",
                routetype: "D",
                hospital:'上海市第一人民医院',
                deadlineapprovel:"2020-11-09 12:45:26",
                depdate: "2020-11-26",
                arrdate: "2020-11-26",
                mobileno: "15000290628",
                jdeno: "d1000",
                IdNo: "310104198212232864",
                CUICode: "110104198212232869",
                profileid: "1537170",
                type: null,
                price: null,
                servicefee: "10.00",
                processfee: "0.00",
                tax: null,
                status: "已取消",
                approvelstatus: "待审批",
                trips: [
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "780.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                ],
                hotels: [],
                trans: [],
                foods: [],
                others: [],
                visas: [],
              },
              {
                seqno: 3,
                clientname: "",
                bookname: "授权人",
                paxname: "授权人2",
                staffno: "d1000",
                routetype: "D",
                hospital:'上海市第一人民医院',
                deadlineapprovel:"2020-11-09 12:45:26",
                depdate: "2020-11-26",
                arrdate: "2020-11-26",
                mobileno: "15000290628",
                jdeno: "d1000",
                IdNo: "310104198212232865",
                CUICode: "110104198212232864",
                profileid: "1537170",
                type: null,
                price: null,
                servicefee: "10.00",
                processfee: "0.00",
                tax: null,
                status: "已取消",
                approvelstatus: "已拒绝",
                trips: [
                  {
                    flightno: "HU7616",
                    depdate: "2020-11-26",
                    deptime: "07:00",
                    depairpot: "上海浦东",
                    depcity: "上海",
                    arrdate: "2020-11-26",
                    arrtime: "09:25",
                    arrairpot: "北京首都",
                    arrcity: "北京",
                    cabinlevel: "经济舱",
                    cabin: "Y",
                    discount: "",
                    price: "1520.00",
                    lowestprice: "490.00",
                    lowestinfo: "HU7616/U舱",
                    rccode: "RC5",
                    dtRcRemark: "最低价格为差旅政策限制舱位/",
                    nottrainrc: null,
                    nottrainrcRemark: null,
                    pnr: "JFPC3Z",
                    ticketno: "",
                    fb: "A",
                    tourcode: "",
                    arrairpotcode: "PEK",
                    depairpotcode: "PVG",
                    isChangeable: true,
                    isRefundable: true,
                    isEndorsable: false,
                    yprice: "1630.00",
                    bookclasslevel: null,
                    highestfare: "1630.00",
                    tax: "50.00",
                    cabindetail: "A",
                    original_ea_no: null,
                    arrtem: "T2",
                    deptem: "T2",
                    ex_no: "XORDER-202011100282",
                    bosslevelfare: "0.00",
                    bosslevelfareref: "",
                    depairpot_en: "Shanghai Pudong ",
                    depcity_en: "Shanghai",
                    arrairpot_en: "Beijing Capital ",
                    arrcity_en: "Beijing",
                    cabinlevel_en: "Economy",
                    triptype: "F",
                    routetype: "D",
                    cccode: "RHQ行政部",
                    cccode2: "",
                    ccid: "",
                    inordercode: "",
                    inorderid: "",
                    seqno: 1,
                    originalexno: null,
                    originaltripsegseqnno: 0,
                    changereasoncode: null,
                    changereasonremark: null,
                    tripchangetimes: "0",
                    recordid: null,
                    changefee: null,
                    upgradefee: null,
                    processfee: null,
                    index: null,
                    tripIndex: null,
                    nonCorpFare: null,
                    baggage: null,
                    mealService: null,
                    mileage: null,
                    duration: null,
                    durationF2: null,
                    durationF3: null,
                    aircraftCode: null,
                    freecanceldeadline: "2020-11-10 14:59:00",
                    paxname: "授权人",
                    change_policy: "",
                    refund_policy: "",
                    travel_purpose: "667",
                    overbudget_reason: "",
                  },
                ],
                hotels: [],
                trans: [],
                foods: [],
                others: [],
                visas: [],
              },
              
            ],
          },
        },
      ],
      approvelDataListEnd: [
        {
          name: "广州淋巴癌会议",
          startTime: "2020-11-11",
          endTime: "2020-11-11",
          meetNum: "EPG567",
          gross: 600000,
          cost: 600000,
        },
        {
          name: "广州淋巴癌会议",
          startTime: "2020-11-11",
          endTime: "2020-11-11",
          meetNum: "EPG567",
          gross: 600000,
          cost: 550000,
        },
      ],
    };
  },
  components: {
    BreadCrumb,
    Slider,
    QuickSearch,
    ApprovelList,
  },
};
</script>

<style>
</style>